apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tortoise-go 
  janus-idp.io/tekton: tortoise-go
  backstage.io/kubernetes-id: tortoise-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tortoise-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  